In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [12]:
df=pd.read_csv(r"C:\Users\asus\Desktop\cardekho_dataset.csv")

In [14]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [27]:
df.drop(columns=['car_name','brand'],axis=1,inplace=True)

In [28]:
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [29]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [38]:
#getting all diff features
num_feature=[feature for feature in df.columns if df[feature].dtype!='O']
print("num_feature:",len(num_feature))
cat_feature=[feature for feature in df.columns if df[feature].dtype=="O"]
print("cat_feature:",len(cat_feature))
discrete_feature=[feature for feature in num_feature if len(df[feature].unique())<=25]
print('discrete_feature:',len(discrete_feature))
continuous_feature=[feature for feature in num_feature if feature not in discrete_feature]
print('continuous_feature:',len(continuous_feature))

num_feature: 7
cat_feature: 4
discrete_feature: 2
continuous_feature: 5

In [41]:
from sklearn.model_selection import train_test_split
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [43]:
#feature encoding

In [46]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [50]:
x['model']=le.fit_transform(x['model'])

In [54]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

In [56]:
num_features=x.select_dtypes(exclude='object').columns
onehot_columns=['seller_type','fuel_type','transmission_type']

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer([
    ("OneHotEncoding",oh_transformer,onehot_columns),
    ("StandardScaler",numeric_transformer,num_features)
],remainder='passthrough')

In [59]:
x=preprocessor.fit_transform(x)

In [60]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#model training and model  selection

In [71]:
from sklearn .ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [78]:
## create a function to evaluate model
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [81]:
#model training
models={'LinearRegression':LinearRegression(),
        'Ridge': Ridge(),
        'Lasso':Lasso(),
        'RandomForestRegressor':RandomForestRegressor(),
        'KNeighborsRegressor': KNeighborsRegressor(),
        'DecisionTreeRegressor':DecisionTreeRegressor()
    }
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    #make prediction

    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)

    #evaluate
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for training set')
    print('-root mean squared error: {:.4f}'.format(model_train_rmse))
    print('-mean absolute error: {:.4f}'.format(model_train_mae))
    print('-r2score : {:.4f}'.format(model_train_r2))

    print('................................................')

    print('Model performance for test set')
    print('-root mean squared error: {:.4f}'.format(model_test_rmse))
    print('-mean absolute error: {:.4f}'.format(model_test_mae))
    print('-r2score : {:.4f}'.format(model_test_r2))
    
    print('='*35)
    print('\n')

LinearRegression
Model performance for training set
-root mean squared error: 553855.6665
-mean absolute error: 268101.6071
-r2score : 0.6218
................................................
Model performance for test set
-root mean squared error: 502543.5930
-mean absolute error: 279618.5794
-r2score : 0.6645
===================================


Ridge
Model performance for training set
-root mean squared error: 553856.3160
-mean absolute error: 268059.8015
-r2score : 0.6218
................................................
Model performance for test set
-root mean squared error: 502533.8230
-mean absolute error: 279557.2169
-r2score : 0.6645
===================================


Lasso
Model performance for training set
-root mean squared error: 553855.6710
-mean absolute error: 268099.2226
-r2score : 0.6218
................................................
Model performance for test set
-root mean squared error: 502542.6696
-mean absolute error: 279614.7461
-r2score : 0.6645
===================================


RandomForestRegressor
Model performance for training set
-root mean squared error: 144889.5000
-mean absolute error: 39951.0441
-r2score : 0.9741
................................................
Model performance for test set
-root mean squared error: 225621.2443
-mean absolute error: 101371.2218
-r2score : 0.9324
===================================


KNeighborsRegressor
Model performance for training set
-root mean squared error: 325873.0088
-mean absolute error: 91425.4705
-r2score : 0.8691
................................................
Model performance for test set
-root mean squared error: 253024.3951
-mean absolute error: 112526.3461
-r2score : 0.9150
===================================


DecisionTreeRegressor
Model performance for training set
-root mean squared error: 20797.2352
-mean absolute error: 5164.8199
-r2score : 0.9995
................................................
Model performance for test set
-root mean squared error: 308049.4624
-mean absolute error: 125252.3705
-r2score : 0.8739
===================================

# hyper parameter tuning for knn and decision forest

In [109]:
#'algorithm':['ball_tree', 'kd_tree','brute','auto'],
            #'weights':['uniform', 'distance']
knn_params={'n_neighbors':[2,3,10,20,40,50]
           }
rf_params={'n_estimators':[100,200,500,1000,],
            'max_depth':[5,8,15,None,10],
            'min_samples_split':[2,8,15,20],
            'max_features':[5,7,8,9,10]
            }

In [110]:
randomcv_models=[('KNN',KNeighborsRegressor(),knn_params),
                 ('RF',RandomForestRegressor(),rf_params)]

In [111]:
from sklearn.model_selection import RandomizedSearchCV

model_param={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              n_iter=25,
                              cv=3,
                              verbose=2,
                              n_jobs=4
                             )
    random.fit(x_train,y_train)
    model_param[name]=random.best_params_

for model_name in model_param:
     print(f'...................best params for{model_name}.........')
     print(model_param[model_name])

C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=25. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 25 candidates, totalling 75 fits
...................best params forKNN.........
{'n_neighbors': 10}
...................best params forRF.........
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}

In [115]:
#model training
models={
        'RandomForestRegressor':RandomForestRegressor(n_estimators=500,min_samples_split= 2,max_features=7,max_depth=15,n_jobs=-1),
        'KNeighborsRegressor': KNeighborsRegressor(n_neighbors=10,n_jobs=-1)
    }
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    #make prediction

    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)

    #evaluate
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for training set')
    print('-root mean squared error: {:.4f}'.format(model_train_rmse))
    print('-mean absolute error: {:.4f}'.format(model_train_mae))
    print('-r2score : {:.4f}'.format(model_train_r2))

    print('................................................')

    print('Model performance for test set')
    print('-root mean squared error: {:.4f}'.format(model_test_rmse))
    print('-mean absolute error: {:.4f}'.format(model_test_mae))
    print('-r2score : {:.4f}'.format(model_test_r2))
    
    print('='*35)
    print('\n')

RandomForestRegressor
Model performance for training set
-root mean squared error: 139655.2245
-mean absolute error: 54732.7615
-r2score : 0.9760
................................................
Model performance for test set
-root mean squared error: 211965.4430
-mean absolute error: 97652.3396
-r2score : 0.9403
===================================


KNeighborsRegressor
Model performance for training set
-root mean squared error: 363460.7706
-mean absolute error: 103472.0474
-r2score : 0.8371
................................................
Model performance for test set
-root mean squared error: 263888.0623
-mean absolute error: 117496.2131
-r2score : 0.9075
===================================